### ISSUE TITLE
App crashes when vocab count is 0 

### ISSUE THREAD

**Issue by CrownKira** [LingoClash/LingoClash#71]
<img width="1008" alt="Screenshot 2022-04-17 at 1 36 53 AM" src="https://user-images.githubusercontent.com/24221801/163685568-0fc3a5ef-642e-4631-97ea-6a157db5a570.png">

**Comment by CrownKira** [comment]
Should not crash the app. Perhaps handle it with an alert ?

**Comment by sherrpass** [comment]
Thanks for the issue. This is intended as a safeguard for devs since we do not wish for empty lessons.
